<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Vicomage\Blog\Block\Sidebar\Recent
 */
?>

<?php
    $_post = $this->getPost();
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <?php echo __('Recent Posts') ?>
    </div>
    <?php foreach ($_postCollection as $_post) { ?>
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="block-content">
                    <div class="post-image">
                        <a href="<?php echo $_post->getPostUrl() ?>" title="<?php echo $block->escapeHtml($_post->getTitle()) ?>">
                            <img src="<?php echo $featuredImage ?>" alt="<?php echo $block->escapeHtml($_post->getTitle()) ?>" />
                        </a>
                    </div>
                <?php } ?>
                <div class="item">
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()) ?>
                    </a>
                    <div class="post-date">
                        <i class="icon-clock"></i>
                        <span class="date-home-month"><?php echo $_post->getPublishDate('M') ?></span>
                        <span class="date-home-day"><?php echo $_post->getPublishDate('j') ?></span>
                    </div>
                </div>
            </div>
    <?php } ?>
</div>
<?php } ?>