<?php $config = $this->getConfig(); ?>
<?php if (isset($config['group'])): ?>
    <?php
    $items = $this->getItems();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    ?>
	<div class="sections vertical-menu">
		<div class="block-title">
			<h4 class="title"><i class="fa fa-bars"></i>Catagories</h4>
		</div>
		<nav class="vertical vicomage-megamenu navigation" role="vertical">
			<ul id="verticalMenu" class="nav nav-main">
				<?php echo $block->getCategorys(); ?>

                <?php if ($items) : ?>
                    <?php foreach ($items as $item) {
                        echo $this->getMegamenuHtml($item);
                    } ?>
                <?php endif; ?>
			</ul>
		</nav>
	</div>
    <script type="text/javascript">
        require([
            'jquery',
            'megamenu'
        ], function ($) {
            $(".vicomage-megamenu").Megamenu();
        });
    </script>
<?php endif; ?>

